const API="https://script.google.com/macros/s/AKfycbybglzC0nFDdVs1T2htNWh1jiIDGq_7Y21zRnzkv5KgQdSKa-5Rs2cgilE-UhtGAdnyXQ/exec";
let S=null, cache={guru:[],siswa:[],kelas:[],mapel:[],jadwal:[]}, editId=null, editType=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function msg(t,ok=false){$("loginMessage").className="message "+(ok?"success":"error");$("loginMessage").textContent=t}
function toast(t){let x=$("toast");x.textContent=t;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),2800)}
async function api(action,payload={}){let r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...payload})});let t=await r.text();try{return JSON.parse(t)}catch(e){throw Error("Respons API tidak dapat dibaca. Periksa koneksi API/CORS.")}}
function unwrap(r){if(Array.isArray(r))return r;if(r&&Array.isArray(r.data))return r.data;if(r&&Array.isArray(r.rows))return r.rows;return []}
async function login(ev){ev.preventDefault();let u=$("username").value.trim(),p=$("password").value,b=$("loginBtn");b.disabled=true;b.textContent="⏳ Memeriksa...";msg("Menghubungkan ke DEV...",true);
try{let g=await api("loginGuru",{username:u,password:p});if(g?.success){S={kind:"guru",idGuru:g.idGuru,namaGuru:g.namaGuru,role:String(g.role||"").toUpperCase(),kelasWali:g.kelasWali||""};sessionStorage.setItem("portalDEV",JSON.stringify(S));showPortal();return}
let a=await api("loginAdmin",{username:u,password:p});if(a?.success){S={kind:"admin",username:a.username,role:"ADMIN_PORTAL"};sessionStorage.setItem("portalDEV",JSON.stringify(S));showPortal();return}
throw Error(a?.message||g?.message||"Username atau password salah.")}catch(e){msg(e.message||"Login gagal.");b.disabled=false;b.textContent="🔐 Masuk"}}
function showPortal(){$("loginPage").classList.add("hidden");$("portalPage").classList.remove("hidden");$("who").textContent=S.kind==="admin"?`${S.username} • ADMIN`: `${S.namaGuru} • ${S.role}`;if(S.kind==="admin"){ $("title").textContent="Dashboard Admin";$("adminNav").classList.remove("hidden");$("adminMain").classList.remove("hidden");loadAdminDashboard()}else{$("title").textContent=S.role==="WALI_KELAS"?"Dashboard Wali Kelas":"Dashboard Guru Mapel";$("guruMain").classList.remove("hidden");if(S.role==="WALI_KELAS"){ $("guruMapelPage").classList.add("hidden");$("waliPage").classList.remove("hidden");loadWali()}else loadGuruMapel()}}
function logout(){sessionStorage.removeItem("portalDEV");location.reload()}
function nav(page){document.querySelectorAll("#adminMain .page").forEach(x=>x.classList.add("hidden"));$("page-"+page).classList.remove("hidden");let m={guru:loadGuru,siswa:loadSiswa,kelas:loadKelas,mapel:loadMapel,jadwal:loadJadwal,absensiGuru:loadAbsensiGuru,absensiSiswa:loadAbsensiSiswa};if(m[page])m[page]()}
async function loadAdminDashboard(){let qs=[["adminGetGuru","nGuru","guru"],["adminGetSiswa","nSiswa","siswa"],["adminGetKelas","nKelas","kelas"],["adminGetMapel","nMapel","mapel"]];await Promise.all(qs.map(async q=>{try{let d=await api(q[0]);cache[q[2]]=unwrap(d);$(q[1]).textContent=cache[q[2]].length}catch(e){$(q[1]).textContent="?";toast(e.message)}}))}
async function loadGuru(){try{let d=unwrap(await api("adminGetGuru"));cache.guru=d;renderTable("guruTable",d,"guru")}catch(e){toast(e.message)}}
async function loadSiswa(){try{let d=unwrap(await api("adminGetSiswa"));cache.siswa=d;renderTable("siswaTable",d,"siswa")}catch(e){toast(e.message)}}
async function loadKelas(){try{let d=unwrap(await api("adminGetKelas"));cache.kelas=d;renderTable("kelasTable",d,"kelas")}catch(e){toast(e.message)}}
async function loadMapel(){try{let d=unwrap(await api("adminGetMapel"));cache.mapel=d;renderTable("mapelTable",d,"mapel")}catch(e){toast(e.message)}}
async function loadJadwal(){try{let d=unwrap(await api("adminGetJadwal"));cache.jadwal=d;renderTable("jadwalTable",d,"jadwal")}catch(e){toast(e.message)}}
async function loadAbsensiGuru(){try{renderTable("absensiGuruTable",unwrap(await api("getAbsensiGuru")),"none")}catch(e){toast(e.message)}}
async function loadAbsensiSiswa(){try{renderTable("absensiSiswaTable",unwrap(await api("getAbsensiSiswa")),"none")}catch(e){toast(e.message)}}
function renderTable(id,rows,type){let el=$(id);if(!rows.length){el.innerHTML='<div class="empty">Tidak ada data.</div>';return}let keys=Object.keys(rows[0]);let show=rows.slice(0,300);el.innerHTML=`<div class="table-wrap"><table class="table"><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join("")}${type!=="none"?'<th>Aksi</th>':""}</tr></thead><tbody>${show.map((r,i)=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join("")}${type!=="none"?`<td><div class="actions"><button class="edit" onclick="editEntity('${type}',${i})">Edit</button><button class="del" onclick="deleteEntity('${type}',${i})">Hapus</button></div></td>`:""}</tr>`).join("")}</tbody></table></div>`}
function field(label,name,value="",opts=""){let type=opts.includes("password")?"password":"text";return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${opts}></label>`}
function select(label,name,value,options,required=true){return `<label>${label}<select name="${name}" ${required?"required":""}><option value="">-- pilih --</option>${options.map(x=>`<option value="${esc(x.v??x)}" ${String(x.v??x)===String(value??"")?"selected":""}>${esc(x.t??x)}</option>`).join("")}</select></label>`}
function openForm(type,row=null){editType=type;editId=row?.id_guru||row?.id_siswa||row?.id_kelas||row?.id_mapel||row?.id_jadwal||null;$("modalTitle").textContent=(row?"Edit ":"Tambah ")+({guru:"Guru",siswa:"Siswa",kelas:"Kelas",mapel:"Mata Pelajaran",jadwal:"Jadwal"}[type]);let f="";
if(type==="guru"){let kelas=cache.kelas.map(x=>({v:x.id_kelas||x[0],t:x.nama_kelas||x[1]}));f=`<div class="form-grid">${field("Nama Guru","nama_guru",row?.nama_guru||"")}${field("Username","username",row?.username||"")}${field("Password baru","password","",row?"password":"required password")} ${select("Role","role",row?.role||"GURU",["GURU","GURU_MAPEL","WALI_KELAS"])} ${select("Kelas Wali","kelas_wali",row?.kelas_wali||"",kelas,false)} ${select("Status","status",row?.status||"AKTIF",["AKTIF","NONAKTIF"])}<div class="full hint">Password kosong saat edit = password lama tetap digunakan. Password baru akan di-hash oleh backend.</div></div>`}
if(type==="siswa"){let ks=cache.kelas.map(x=>({v:x.id_kelas||x[0],t:x.nama_kelas||x[1]}));f=`<div class="form-grid">${field("NIS","nis",row?.nis||"")}${field("NISN","nisn",row?.nisn||"")}${field("Nama Siswa","nama",row?.nama_siswa||row?.nama||"")}${select("Jenis Kelamin","jk",row?.jk||"",["L","P"])}${select("Kelas","kelas",row?.id_kelas||row?.kelas||"",ks)}${field("Tempat, Tanggal Lahir","tempat_tanggal_lahir",row?.tempat_tanggal_lahir||"")}${field("Agama","agama",row?.agama||"")}${field("Nama Orang Tua","nama_orang_tua",row?.nama_orang_tua||"")}${select("Status","status",row?.status||"AKTIF",["AKTIF","NONAKTIF"])}</div>`}
if(type==="kelas"){let gs=cache.guru.map(x=>({v:x.id_guru,t:x.nama_guru}));f=`<div class="form-grid">${field("Nama Kelas","nama_kelas",row?.nama_kelas||"")}${select("Wali Kelas","id_wali_kelas",row?.id_wali_kelas||"",gs,false)}${select("Status","status",row?.status||"AKTIF",["AKTIF","NONAKTIF"])}</div>`}
if(type==="mapel")f=`<div class="form-grid">${field("Nama Mata Pelajaran","nama_mapel",row?.nama_mapel||"")}${select("Status","status",row?.status||"AKTIF",["AKTIF","NONAKTIF"])}</div>`;
if(type==="jadwal"){let gs=cache.guru.map(x=>({v:x.id_guru,t:x.nama_guru})),ks=cache.kelas.map(x=>({v:x.id_kelas||x[0],t:x.nama_kelas||x[1]})),ms=cache.mapel.map(x=>({v:x.id_mapel||x[0],t:x.nama_mapel||x[1]}));f=`<div class="form-grid">${select("Guru","id_guru",row?.id_guru||"",gs)}${select("Kelas","id_kelas",row?.id_kelas||"",ks)}${select("Mapel","id_mapel",row?.id_mapel||"",ms)}${field("Jam Pelajaran","jam_pelajaran",row?.jam_pelajaran||"")}${select("Hari","hari",row?.hari||"",["SENIN","SELASA","RABU","KAMIS","JUMAT","SABTU"])}</div>`}
$("entityForm").innerHTML=f+`<div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">Batal</button><button class="primary">💾 Simpan</button></div>`;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden");$("entityForm").innerHTML=""}
async function saveEntity(e){e.preventDefault();let fd=new FormData(e.target),o=Object.fromEntries(fd.entries()),isEdit=!!editId,action,args=[];
if(editType==="guru"){action=isEdit?"adminEditGuru":"adminTambahGuru";if(isEdit)o.id_guru=editId;args=[o]}
if(editType==="siswa"){action=isEdit?"adminEditSiswa":"adminTambahSiswa";if(isEdit)o.id_siswa=editId;args=[o]}
if(editType==="kelas"){action=isEdit?"adminEditKelas":"adminTambahKelas";if(isEdit)o.id_kelas=editId;args=[o]}
if(editType==="mapel"){action=isEdit?"adminEditMapel":"adminTambahMapel";if(isEdit)o.id_mapel=editId;args=[o]}
if(editType==="jadwal"){action=isEdit?"adminEditJadwal":"adminTambahJadwal";if(isEdit)o.id_jadwal=editId;args=[o]}
try{let r=await api(action,{args});if(!r.success)throw Error(r.message||"Gagal menyimpan");toast(r.message||"Tersimpan");closeModal();nav(editType)}catch(err){toast(err.message)}}
async function deleteEntity(type,i){let arr=cache[type],r=arr[i],id=r.id_guru||r.id_siswa||r.id_kelas||r.id_mapel||r.id_jadwal;if(!confirm(`Hapus data ${id}?`))return;let action={guru:"adminHapusGuru",siswa:"adminHapusSiswa",kelas:"adminHapusKelas",mapel:"adminHapusMapel",jadwal:"adminHapusJadwal"}[type];try{let z=await api(action,{args:[id]});if(!z.success)throw Error(z.message||"Gagal menghapus");toast(z.message||"Terhapus");nav(type);loadAdminDashboard()}catch(e){toast(e.message)}}
function editEntity(type,i){openForm(type,cache[type][i])}
async function loadGuruMapel(){try{let d=await api("getDashboardGuruMapel",{idGuru:S.idGuru});if(!d.success)throw Error(d.message);$("gHari").textContent=d.hari||"-";$("gJadwal").textContent=d.jumlahJadwal??0;$("gKelas").textContent=d.jumlahKelas??0;let a=d.jadwal||[];$("scheduleCards").innerHTML=a.length?a.map(j=>`<div class="card"><h4>${esc(j.nama_mapel||j.id_mapel)}</h4><p>🏫 ${esc(j.nama_kelas||j.id_kelas)}</p><p>🕐 ${esc(j.jam_pelajaran)}</p><button class="ghost" onclick="openGuruAttendance('${esc(j.id_jadwal)}')">Buka Absensi</button></div>`).join(""):'<div class="empty">Tidak ada jadwal hari ini.</div>'}catch(e){toast(e.message)}}
async function openGuruAttendance(id){try{let d=await api("getSiswaUntukJadwalGuru",{idGuru:S.idGuru,idJadwal:id});if(!d.success)throw Error(d.message);$("gaTitle").textContent=d.jadwal.nama_mapel||"Absensi";$("gaInfo").textContent=`${d.jadwal.nama_kelas||""} • ${d.jadwal.jam_pelajaran||""}`;renderStudents("gaStudents",d.siswa||[],(sid,st,b)=>saveGuruAbs(id,sid,st,b));$("guruAttendance").classList.remove("hidden")}catch(e){toast(e.message)}}
async function saveGuruAbs(j,sid,st,b){b.disabled=true;try{let r=await api("simpanAbsensiGuruMapel",{data:{idGuru:S.idGuru,idJadwal:j,idSiswa:sid,status:st}});if(!r.success)throw Error(r.message);b.parentElement.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");toast(r.message||"Absensi tersimpan")}catch(e){toast(e.message)}finally{b.disabled=false}}
async function loadWali(){try{let d=await api("getAbsensiHariIniWaliKelas",{idGuru:S.idGuru});if(!d.success)throw Error(d.message);$("wTitle").textContent=d.kelas?.namaKelas?`Wali Kelas ${d.kelas.namaKelas}`:"Wali Kelas";$("wDate").textContent=d.tanggal||"-";$("wSiswa").textContent=d.jumlahSiswa??0;$("wHadir").textContent=d.rekap?.hadir??0;$("wSakit").textContent=d.rekap?.sakit??0;$("wLain").textContent=(d.rekap?.izin||0)+(d.rekap?.alpa||0);renderStudents("wStudents",d.siswa||[],(sid,st,b)=>saveWali(sid,st,b))}catch(e){toast(e.message)}}
async function saveWali(sid,st,b){b.disabled=true;try{let r=await api("simpanAbsensiWaliKelas",{data:{idGuru:S.idGuru,idSiswa:sid,status:st}});if(!r.success)throw Error(r.message);b.parentElement.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");toast(r.message||"Absensi tersimpan")}catch(e){toast(e.message)}finally{b.disabled=false}}
function renderStudents(id,a,fn){let c=$(id);if(!a.length){c.innerHTML='<div class="empty">Belum ada siswa.</div>';return}c.innerHTML=a.map(s=>`<div class="student"><div><h4>${esc(s.nama_siswa||s.nama||"-")}</h4><p>NIS: ${esc(s.nis||"-")}</p></div><div class="status-btns">${["HADIR","IZIN","SAKIT","ALPA"].map(x=>`<button data-st="${x}">${x}</button>`).join("")}</div></div>`).join("");c.querySelectorAll("[data-st]").forEach(b=>b.onclick=()=>fn(a[[...c.querySelectorAll(".student")].indexOf(b.closest(".student"))].id_siswa,b.dataset.st,b))}
$("loginForm").onsubmit=login;$("logout").onclick=logout;$("refreshStats").onclick=loadAdminDashboard;$("refreshGuru").onclick=loadGuruMapel;$("refreshWali").onclick=loadWali;$("closeGa").onclick=()=>$("guruAttendance").classList.add("hidden");$("modalClose").onclick=closeModal;$("entityForm").onsubmit=saveEntity;
document.querySelectorAll("#adminNav button").forEach(b=>b.onclick=()=>nav(b.dataset.page));document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>openForm(b.dataset.add));document.querySelectorAll("[data-refresh]").forEach(b=>b.onclick=()=>({absensiGuru:loadAbsensiGuru,absensiSiswa:loadAbsensiSiswa}[b.dataset.refresh])());
try{let q=JSON.parse(sessionStorage.getItem("portalDEV")||"null");if(q){S=q;showPortal()}}catch(e){}