const SCRIPT_URL="https://script.google.com/macros/s/AKfycbybglzC0nFDdVs1T2htNWh1jiIDGq_7Y21zRnzkv5KgQdSKa-5Rs2cgilE-UhtGAdnyXQ/exec";
const SESSION_KEY="portalGuruSessionDEV",$=id=>document.getElementById(id);let session=null;
function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2800)}function loading(x){$("loadingBox").classList.toggle("hidden",!x)}
async function api(action,payload={}){const r=await fetch(SCRIPT_URL,{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...payload})});if(!r.ok)throw Error("HTTP "+r.status);const t=await r.text();try{return JSON.parse(t)}catch{throw Error("Respons API tidak dapat dibaca. Jika muncul CORS / Failed to fetch, hentikan test dan laporkan error.")}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function save(d){session={idGuru:d.idGuru||d.id_guru||"",namaGuru:d.namaGuru||d.nama_guru||"",role:String(d.role||"").trim().toUpperCase(),kelasWali:d.kelasWali||d.kelas_wali||""};sessionStorage.setItem(SESSION_KEY,JSON.stringify(session))}function restore(){try{let x=JSON.parse(sessionStorage.getItem(SESSION_KEY)||"null");if(x?.idGuru)session=x}catch{}}
async function login(e){e.preventDefault();const u=$("username").value.trim(),p=$("password").value,b=$("loginBtn"),m=$("loginMessage");b.disabled=true;b.textContent="⏳ Memeriksa...";m.className="message";m.textContent="Menghubungkan ke Portal DEV...";try{const d=await api("loginGuru",{username:u,password:p});$("password").value="";if(!d?.success)throw Error(d?.message||"Username atau password salah.");save(d);m.className="message success";m.textContent="✓ Login berhasil.";await openApp()}catch(x){m.className="message error";m.textContent=x.message||"Login gagal."}finally{b.disabled=false;b.textContent="🔐 Masuk"}}
async function openApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("guruInfo").textContent=`${session.namaGuru||session.idGuru} • ${session.role||"GURU"}`;$("mapelView").classList.add("hidden");$("waliView").classList.add("hidden");if(session.role==="WALI_KELAS"){$("pageTitle").textContent="Dashboard Wali Kelas";$("waliView").classList.remove("hidden");await loadWali()}else{$("pageTitle").textContent="Dashboard Guru Mapel";$("mapelView").classList.remove("hidden");await loadMapel()}}
async function loadMapel(){loading(true);try{const d=await api("getDashboardGuruMapel",{idGuru:session.idGuru});if(!d?.success)throw Error(d?.message||"Dashboard gagal dimuat.");$("mapelHari").textContent=d.hari||"-";$("jumlahJadwal").textContent=d.jumlahJadwal??(d.jadwal||[]).length;$("jumlahKelas").textContent=d.jumlahKelas??(d.kelas||[]).length;const l=$("jadwalList"),rows=d.jadwal||[];l.innerHTML=rows.length?rows.map(j=>`<article class="schedule"><h4>${esc(j.nama_mapel||j.namaMapel||j.id_mapel||"Mata Pelajaran")}</h4><p>🏫 ${esc(j.nama_kelas||j.namaKelas||j.id_kelas||"-")}</p><p>🕐 ${esc(j.jam_pelajaran||j.jamPelajaran||"-")}</p><button data-j="${esc(j.id_jadwal||j.idJadwal||"")}">Buka Absensi →</button></article>`).join(""):'<div class="empty">Tidak ada jadwal mengajar untuk hari ini.</div>';l.querySelectorAll("[data-j]").forEach(b=>b.onclick=()=>loadStudents(b.dataset.j))}catch(e){toast(e.message)}finally{loading(false)}}
async function loadStudents(idJadwal){loading(true);try{const d=await api("getSiswaUntukJadwalGuru",{idGuru:session.idGuru,idJadwal});if(!d?.success)throw Error(d?.message||"Data siswa gagal dimuat.");$("judulJadwal").textContent=d.jadwal?.nama_mapel||d.jadwal?.namaMapel||"Absensi Siswa";$("detailJadwal").textContent=`${d.jadwal?.nama_kelas||d.jadwal?.namaKelas||""} • ${d.jadwal?.jam_pelajaran||d.jadwal?.jamPelajaran||""}`;render($("siswaMapelList"),d.siswa||[],(sid,st,b)=>saveMapel(idJadwal,sid,st,b));$("absenMapelPanel").classList.remove("hidden");$("absenMapelPanel").scrollIntoView({behavior:"smooth"})}catch(e){toast(e.message)}finally{loading(false)}}
async function saveMapel(j,s,st,b){lock(b,true);try{const d=await api("simpanAbsensiGuruMapel",{data:{idGuru:session.idGuru,idJadwal:j,idSiswa:s,status:st}});if(!d?.success)throw Error(d?.message||"Gagal menyimpan.");active(b);toast(d.message||"Absensi tersimpan.")}catch(e){toast(e.message)}finally{lock(b,false)}}
async function loadWali(){loading(true);try{const d=await api("getAbsensiHariIniWaliKelas",{idGuru:session.idGuru});if(!d?.success)throw Error(d?.message||"Dashboard Wali gagal dimuat.");$("waliKelas").textContent=d.kelas?.namaKelas?"Kelas "+d.kelas.namaKelas:"Wali Kelas";$("waliTanggal").textContent=d.tanggal||"Absensi hari ini";$("waliJumlah").textContent=d.jumlahSiswa??(d.siswa||[]).length;$("waliHadir").textContent=d.rekap?.hadir??0;$("waliSakit").textContent=d.rekap?.sakit??0;$("waliLain").textContent=Number(d.rekap?.izin||0)+Number(d.rekap?.alpa||0);render($("siswaWaliList"),d.siswa||[],saveWali)}catch(e){toast(e.message)}finally{loading(false)}}
async function saveWali(s,st,b){lock(b,true);try{const d=await api("simpanAbsensiWaliKelas",{data:{idGuru:session.idGuru,idSiswa:s,status:st}});if(!d?.success)throw Error(d?.message||"Gagal menyimpan.");active(b);toast(d.message||"Absensi tersimpan.");await loadWali()}catch(e){toast(e.message)}finally{lock(b,false)}}
function render(c,a,fn){if(!a.length){c.innerHTML='<div class="empty">Belum ada siswa pada data ini.</div>';return}c.innerHTML=a.map(s=>{let id=s.id_siswa||s.idSiswa||"",cur=String(s.status_absensi||s.statusAbsensi||s.absensi||"").toUpperCase();return `<article class="student"><div><h4>${esc(s.nama_siswa||s.namaSiswa||s.nama||"-")}</h4><p>NIS: ${esc(s.nis||"-")} • ${esc(s.nama_kelas||s.namaKelas||"")}</p></div><div class="status-actions">${["HADIR","IZIN","SAKIT","ALPA"].map(st=>`<button class="${cur===st?"active":""}" data-st="${st}" data-id="${esc(id)}">${st}</button>`).join("")}</div></article>`}).join("");c.querySelectorAll("[data-st]").forEach(b=>b.onclick=()=>fn(b.dataset.id,b.dataset.st,b))}function lock(b,x){b.closest(".student")?.querySelectorAll("button").forEach(q=>q.disabled=x)}function active(b){b.closest(".student")?.querySelectorAll("button").forEach(q=>q.classList.remove("active"));b.classList.add("active")}
$("loginForm").onsubmit=login;$("logoutBtn").onclick=()=>{sessionStorage.removeItem(SESSION_KEY);location.reload()};$("refreshMapel").onclick=loadMapel;$("refreshWali").onclick=loadWali;$("tutupJadwal").onclick=()=>$("absenMapelPanel").classList.add("hidden");restore();if(session)openApp();
